local g = vim.g
local o = vim.opt

g.mapleader    = " "
o.number       = true
o.clipboard    = "unnamedplus"
o.syntax       = "on"
o.autoindent   = true
o.expandtab    = true
o.shiftwidth   = 2
o.tabstop      = 2
o.encoding     = "UTF-8"
o.ruler        = true
o.mouse        = "a"
o.title        = true
o.hidden       = true
o.ttimeoutlen  = 0
o.showmatch    = true
o.inccommand   = "split"
o.splitright   = true
o.splitbelow   = false
o.cursorline   = true
